#local profile
server:
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: local
      
  application:
    name: moun
    
  datasource:
    url: jdbc:mysql://localhost:3306/moun
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #change to none after create once
    show-sql: true
    properties:
      hibernate:
        format_sql: false #show jpa query log
    open-in-view: false
  
  sql:
    init:
      mode: never #after initialize hibernate, do sql query(data.sql)
  main:
    banner-mode: off


---
# test profile
spring:
  config:
    activate:
      on-profile: test
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  sql:
    init:
      mode: never